# Generated by Django 3.1.2 on 2020-11-01 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('img_url', models.CharField(max_length=300)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searches.productsearch')),
            ],
        ),
    ]
