# Generated by Django 3.1.2 on 2020-11-02 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0002_auto_20201101_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='previous_prices',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
    ]
