# Generated by Django 3.1.2 on 2020-11-02 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0003_productmodel_previous_prices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='previous_prices',
        ),
    ]
